---
title: "Shopping list"
date: today
format: 
  pdf: 
    echo: false
params: 
  recipes: "NA"
  db_path: "NA"
---

```{r}
con <- DBI::dbConnect(
    RSQLite::SQLite(),
    params$db_path
  )
```

```{r}
selected_recipe_names <- params$recipes
```

```{r}
data_all_recipes <- dplyr::tbl(con, "recipe_metadata") |>
        dplyr::filter(recipe_name %in% selected_recipe_names) |>
        dplyr::inner_join(dplyr::tbl(con, "ingredients_in_recipes"),
          by = "recipe_id",
          copy = TRUE
        ) |>
        dplyr::inner_join(dplyr::tbl(con, "ingredients"),
          by = "ingredient_id",
          copy = TRUE
        ) |>
        dplyr::inner_join(dplyr::tbl(con, "units"),
          by = "unit_id",
          copy = TRUE
        ) |>
        dplyr::select(recipe_name, ingredient, amount, unit, preparation) |>
        dplyr::collect()
```

### Selected recipes

```{r}
data.frame(
  recipe = params$recipes
  ) |> 
  kableExtra::kbl("latex", booktabs = T) |> 
  kableExtra::kable_styling(latex_options = c("striped", "hold_position"))
```


### List of ingredients needed for the selected recipes

```{r}
 data_all_recipes |>
  dplyr::summarise(
    .by = c(ingredient, unit),
    amount = sum(amount)
  ) |> 
  kableExtra::kbl("latex", booktabs = T) |> 
  kableExtra::kable_styling(latex_options = c("striped", "hold_position"))
  
```

